-- =============================================================================
-- Wakdo — Seed 0003 : Ingredients + recettes (product_ingredient)
-- =============================================================================
-- Active le decrement de stock (RG-T20) au paiement et la dispo calculee
-- (RG-T21). Catalogue d'ingredients ferme + une recette par produit (53).
-- FK resolus par sous-requete sur le nom (convention seed 0002). INSERT IGNORE
-- => idempotent (UNIQUE name sur ingredient ; PK (product_id,ingredient_id)).
-- Quantites : burger/wrap/salade normal==maxi ; frites/boissons maxi>=normal.
-- Lignes quantity_normal=0 (extras hors base) ecartees : CHECK quantity_normal>0.
-- =============================================================================

SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 1. ingredient (catalogue, stock plein)
INSERT IGNORE INTO ingredient (name, unit, stock_quantity, stock_capacity) VALUES
  ('Pain burger', 'piece', 300, 300),
  ('Pain sesame', 'piece', 300, 300),
  ('Pain signature', 'piece', 250, 250),
  ('Tortilla', 'piece', 200, 200),
  ('Steak hache', 'piece', 400, 400),
  ('Filet de poulet pane', 'piece', 300, 300),
  ('Galette de poisson', 'piece', 150, 150),
  ('Tranche de bacon', 'piece', 500, 500),
  ('Nugget de poulet', 'piece', 1500, 1500),
  ('Jambon', 'tranche', 200, 200),
  ('Cheddar', 'tranche', 600, 600),
  ('Fromage de chevre', 'portion', 150, 150),
  ('Mozzarella', 'portion', 150, 150),
  ('Emmental', 'tranche', 250, 250),
  ('Salade', 'portion', 600, 600),
  ('Tomate', 'rondelle', 400, 400),
  ('Oignon', 'portion', 600, 600),
  ('Cornichon', 'rondelle', 800, 800),
  ('Roquette', 'portion', 200, 200),
  ('Sauce Big Mac', 'dose', 1000, 1000),
  ('Sauce ranch', 'dose', 1000, 1000),
  ('Sauce barbecue', 'dose', 1000, 1000),
  ('Sauce deluxe', 'dose', 1000, 1000),
  ('Pomme de terre frite', 'portion', 3000, 3000),
  ('Galette de pomme de terre', 'portion', 1000, 1000),
  ('Dose Coca', 'dose', 1500, 1500),
  ('Dose Coca Zero', 'dose', 1000, 1000),
  ('Dose Eau', 'dose', 800, 800),
  ('Dose Fanta', 'dose', 1000, 1000),
  ('Dose Ice Tea Peche', 'dose', 1000, 1000),
  ('Dose Ice Tea Citron', 'dose', 800, 800),
  ('Dose Jus d Orange', 'dose', 400, 400),
  ('Dose Jus de Pomme', 'dose', 400, 400),
  ('Gobelet', 'piece', 3000, 3000),
  ('Brownie', 'piece', 150, 150),
  ('Cheesecake', 'piece', 150, 150),
  ('Cookie', 'piece', 150, 150),
  ('Donut', 'piece', 150, 150),
  ('Macaron', 'piece', 200, 200),
  ('Glace McFleury', 'piece', 200, 200),
  ('Muffin', 'piece', 150, 150),
  ('Glace sundae', 'piece', 200, 200),
  ('Topping chocolat', 'dose', 300, 300),
  ('Dosette Barbecue', 'dosette', 1500, 1500),
  ('Dosette Moutarde', 'dosette', 1500, 1500),
  ('Dosette Deluxe', 'dosette', 1500, 1500),
  ('Dosette Ketchup', 'dosette', 2000, 2000),
  ('Dosette Chinoise', 'dosette', 1000, 1000),
  ('Dosette Curry', 'dosette', 1500, 1500),
  ('Dosette Pommes Frites', 'dosette', 1500, 1500);

-- 2. product_ingredient (recettes ; FK par nom)
INSERT IGNORE INTO product_ingredient (product_id, ingredient_id, quantity_normal, quantity_maxi, is_removable, is_addable, extra_price_cents) VALUES
  ((SELECT id FROM product WHERE name='Le 280'), (SELECT id FROM ingredient WHERE name='Pain signature'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Le 280'), (SELECT id FROM ingredient WHERE name='Steak hache'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Le 280'), (SELECT id FROM ingredient WHERE name='Cheddar'), 2, 2, 1, 1, 60),
  ((SELECT id FROM product WHERE name='Le 280'), (SELECT id FROM ingredient WHERE name='Oignon'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Le 280'), (SELECT id FROM ingredient WHERE name='Salade'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Le 280'), (SELECT id FROM ingredient WHERE name='Sauce barbecue'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Big Tasty'), (SELECT id FROM ingredient WHERE name='Pain sesame'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Big Tasty'), (SELECT id FROM ingredient WHERE name='Steak hache'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Big Tasty'), (SELECT id FROM ingredient WHERE name='Emmental'), 2, 2, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Big Tasty'), (SELECT id FROM ingredient WHERE name='Salade'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Big Tasty'), (SELECT id FROM ingredient WHERE name='Tomate'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Big Tasty'), (SELECT id FROM ingredient WHERE name='Oignon'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Big Tasty'), (SELECT id FROM ingredient WHERE name='Sauce barbecue'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Big Tasty Bacon'), (SELECT id FROM ingredient WHERE name='Pain sesame'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Big Tasty Bacon'), (SELECT id FROM ingredient WHERE name='Steak hache'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Big Tasty Bacon'), (SELECT id FROM ingredient WHERE name='Tranche de bacon'), 2, 2, 1, 1, 80),
  ((SELECT id FROM product WHERE name='Big Tasty Bacon'), (SELECT id FROM ingredient WHERE name='Emmental'), 2, 2, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Big Tasty Bacon'), (SELECT id FROM ingredient WHERE name='Salade'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Big Tasty Bacon'), (SELECT id FROM ingredient WHERE name='Tomate'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Big Tasty Bacon'), (SELECT id FROM ingredient WHERE name='Oignon'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Big Tasty Bacon'), (SELECT id FROM ingredient WHERE name='Sauce barbecue'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Big Mac'), (SELECT id FROM ingredient WHERE name='Pain sesame'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Big Mac'), (SELECT id FROM ingredient WHERE name='Steak hache'), 2, 2, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Big Mac'), (SELECT id FROM ingredient WHERE name='Cheddar'), 1, 1, 1, 1, 60),
  ((SELECT id FROM product WHERE name='Big Mac'), (SELECT id FROM ingredient WHERE name='Salade'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Big Mac'), (SELECT id FROM ingredient WHERE name='Oignon'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Big Mac'), (SELECT id FROM ingredient WHERE name='Cornichon'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Big Mac'), (SELECT id FROM ingredient WHERE name='Sauce Big Mac'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='CBO'), (SELECT id FROM ingredient WHERE name='Pain signature'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='CBO'), (SELECT id FROM ingredient WHERE name='Filet de poulet pane'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='CBO'), (SELECT id FROM ingredient WHERE name='Tranche de bacon'), 2, 2, 1, 1, 80),
  ((SELECT id FROM product WHERE name='CBO'), (SELECT id FROM ingredient WHERE name='Emmental'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='CBO'), (SELECT id FROM ingredient WHERE name='Oignon'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='CBO'), (SELECT id FROM ingredient WHERE name='Salade'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='CBO'), (SELECT id FROM ingredient WHERE name='Sauce barbecue'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='MC Chicken'), (SELECT id FROM ingredient WHERE name='Pain sesame'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='MC Chicken'), (SELECT id FROM ingredient WHERE name='Filet de poulet pane'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='MC Chicken'), (SELECT id FROM ingredient WHERE name='Salade'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='MC Chicken'), (SELECT id FROM ingredient WHERE name='Sauce ranch'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='MC Crispy'), (SELECT id FROM ingredient WHERE name='Pain signature'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='MC Crispy'), (SELECT id FROM ingredient WHERE name='Filet de poulet pane'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='MC Crispy'), (SELECT id FROM ingredient WHERE name='Salade'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='MC Crispy'), (SELECT id FROM ingredient WHERE name='Tomate'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='MC Crispy'), (SELECT id FROM ingredient WHERE name='Sauce deluxe'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='MC Fish'), (SELECT id FROM ingredient WHERE name='Pain burger'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='MC Fish'), (SELECT id FROM ingredient WHERE name='Galette de poisson'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='MC Fish'), (SELECT id FROM ingredient WHERE name='Cheddar'), 1, 1, 1, 1, 60),
  ((SELECT id FROM product WHERE name='MC Fish'), (SELECT id FROM ingredient WHERE name='Sauce deluxe'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Royal Bacon'), (SELECT id FROM ingredient WHERE name='Pain sesame'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Royal Bacon'), (SELECT id FROM ingredient WHERE name='Steak hache'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Royal Bacon'), (SELECT id FROM ingredient WHERE name='Tranche de bacon'), 2, 2, 1, 1, 80),
  ((SELECT id FROM product WHERE name='Royal Bacon'), (SELECT id FROM ingredient WHERE name='Cheddar'), 1, 1, 1, 1, 60),
  ((SELECT id FROM product WHERE name='Royal Bacon'), (SELECT id FROM ingredient WHERE name='Salade'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Royal Bacon'), (SELECT id FROM ingredient WHERE name='Oignon'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Royal Bacon'), (SELECT id FROM ingredient WHERE name='Sauce barbecue'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Royal Cheese'), (SELECT id FROM ingredient WHERE name='Pain sesame'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Royal Cheese'), (SELECT id FROM ingredient WHERE name='Steak hache'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Royal Cheese'), (SELECT id FROM ingredient WHERE name='Cheddar'), 2, 2, 1, 1, 60),
  ((SELECT id FROM product WHERE name='Royal Cheese'), (SELECT id FROM ingredient WHERE name='Oignon'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Royal Cheese'), (SELECT id FROM ingredient WHERE name='Cornichon'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Royal Cheese'), (SELECT id FROM ingredient WHERE name='Sauce barbecue'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Royal Deluxe'), (SELECT id FROM ingredient WHERE name='Pain sesame'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Royal Deluxe'), (SELECT id FROM ingredient WHERE name='Steak hache'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Royal Deluxe'), (SELECT id FROM ingredient WHERE name='Cheddar'), 1, 1, 1, 1, 60),
  ((SELECT id FROM product WHERE name='Royal Deluxe'), (SELECT id FROM ingredient WHERE name='Salade'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Royal Deluxe'), (SELECT id FROM ingredient WHERE name='Tomate'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Royal Deluxe'), (SELECT id FROM ingredient WHERE name='Cornichon'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Royal Deluxe'), (SELECT id FROM ingredient WHERE name='Sauce deluxe'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Signature BBQ Beef 2 viandes'), (SELECT id FROM ingredient WHERE name='Pain signature'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Signature BBQ Beef 2 viandes'), (SELECT id FROM ingredient WHERE name='Steak hache'), 2, 2, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Signature BBQ Beef 2 viandes'), (SELECT id FROM ingredient WHERE name='Cheddar'), 2, 2, 1, 1, 60),
  ((SELECT id FROM product WHERE name='Signature BBQ Beef 2 viandes'), (SELECT id FROM ingredient WHERE name='Tranche de bacon'), 2, 2, 1, 1, 80),
  ((SELECT id FROM product WHERE name='Signature BBQ Beef 2 viandes'), (SELECT id FROM ingredient WHERE name='Oignon'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Signature BBQ Beef 2 viandes'), (SELECT id FROM ingredient WHERE name='Salade'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Signature BBQ Beef 2 viandes'), (SELECT id FROM ingredient WHERE name='Sauce barbecue'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Signature Beef BBQ'), (SELECT id FROM ingredient WHERE name='Pain signature'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Signature Beef BBQ'), (SELECT id FROM ingredient WHERE name='Steak hache'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Signature Beef BBQ'), (SELECT id FROM ingredient WHERE name='Cheddar'), 1, 1, 1, 1, 60),
  ((SELECT id FROM product WHERE name='Signature Beef BBQ'), (SELECT id FROM ingredient WHERE name='Oignon'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Signature Beef BBQ'), (SELECT id FROM ingredient WHERE name='Salade'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Signature Beef BBQ'), (SELECT id FROM ingredient WHERE name='Sauce barbecue'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Coca Cola'), (SELECT id FROM ingredient WHERE name='Gobelet'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Coca Cola'), (SELECT id FROM ingredient WHERE name='Dose Coca'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Coca Sans Sucres'), (SELECT id FROM ingredient WHERE name='Gobelet'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Coca Sans Sucres'), (SELECT id FROM ingredient WHERE name='Dose Coca Zero'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Eau'), (SELECT id FROM ingredient WHERE name='Dose Eau'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Fanta Orange'), (SELECT id FROM ingredient WHERE name='Gobelet'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Fanta Orange'), (SELECT id FROM ingredient WHERE name='Dose Fanta'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Ice Tea Peche'), (SELECT id FROM ingredient WHERE name='Gobelet'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Ice Tea Peche'), (SELECT id FROM ingredient WHERE name='Dose Ice Tea Peche'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Ice Tea Citron'), (SELECT id FROM ingredient WHERE name='Gobelet'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Ice Tea Citron'), (SELECT id FROM ingredient WHERE name='Dose Ice Tea Citron'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Jus d''Orange'), (SELECT id FROM ingredient WHERE name='Gobelet'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Jus d''Orange'), (SELECT id FROM ingredient WHERE name='Dose Jus d Orange'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Jus de Pommes Bio'), (SELECT id FROM ingredient WHERE name='Gobelet'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Jus de Pommes Bio'), (SELECT id FROM ingredient WHERE name='Dose Jus de Pomme'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Petite Frite'), (SELECT id FROM ingredient WHERE name='Pomme de terre frite'), 1, 2, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Moyenne Frite'), (SELECT id FROM ingredient WHERE name='Pomme de terre frite'), 2, 3, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Grande Frite'), (SELECT id FROM ingredient WHERE name='Pomme de terre frite'), 3, 4, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Potatoes'), (SELECT id FROM ingredient WHERE name='Galette de pomme de terre'), 2, 3, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Grande Potatoes'), (SELECT id FROM ingredient WHERE name='Galette de pomme de terre'), 3, 4, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Cheeseburger'), (SELECT id FROM ingredient WHERE name='Pain burger'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Cheeseburger'), (SELECT id FROM ingredient WHERE name='Steak hache'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Cheeseburger'), (SELECT id FROM ingredient WHERE name='Cheddar'), 1, 1, 1, 1, 60),
  ((SELECT id FROM product WHERE name='Cheeseburger'), (SELECT id FROM ingredient WHERE name='Oignon'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Cheeseburger'), (SELECT id FROM ingredient WHERE name='Cornichon'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Cheeseburger'), (SELECT id FROM ingredient WHERE name='Sauce Big Mac'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Croc MCdo'), (SELECT id FROM ingredient WHERE name='Pain burger'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Croc MCdo'), (SELECT id FROM ingredient WHERE name='Jambon'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Croc MCdo'), (SELECT id FROM ingredient WHERE name='Emmental'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Nuggets x4'), (SELECT id FROM ingredient WHERE name='Nugget de poulet'), 4, 4, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Nuggets x20'), (SELECT id FROM ingredient WHERE name='Nugget de poulet'), 20, 20, 0, 0, 0),
  ((SELECT id FROM product WHERE name='MC Wrap Chevre'), (SELECT id FROM ingredient WHERE name='Tortilla'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='MC Wrap Chevre'), (SELECT id FROM ingredient WHERE name='Filet de poulet pane'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='MC Wrap Chevre'), (SELECT id FROM ingredient WHERE name='Fromage de chevre'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='MC Wrap Chevre'), (SELECT id FROM ingredient WHERE name='Salade'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='MC Wrap Chevre'), (SELECT id FROM ingredient WHERE name='Tomate'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='MC Wrap Chevre'), (SELECT id FROM ingredient WHERE name='Sauce ranch'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='MC Wrap Poulet Bacon'), (SELECT id FROM ingredient WHERE name='Tortilla'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='MC Wrap Poulet Bacon'), (SELECT id FROM ingredient WHERE name='Filet de poulet pane'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='MC Wrap Poulet Bacon'), (SELECT id FROM ingredient WHERE name='Tranche de bacon'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='MC Wrap Poulet Bacon'), (SELECT id FROM ingredient WHERE name='Cheddar'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='MC Wrap Poulet Bacon'), (SELECT id FROM ingredient WHERE name='Salade'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='MC Wrap Poulet Bacon'), (SELECT id FROM ingredient WHERE name='Tomate'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='MC Wrap Poulet Bacon'), (SELECT id FROM ingredient WHERE name='Sauce barbecue'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Ptit Wrap Chevre'), (SELECT id FROM ingredient WHERE name='Tortilla'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Ptit Wrap Chevre'), (SELECT id FROM ingredient WHERE name='Filet de poulet pane'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Ptit Wrap Chevre'), (SELECT id FROM ingredient WHERE name='Fromage de chevre'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Ptit Wrap Chevre'), (SELECT id FROM ingredient WHERE name='Salade'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Ptit Wrap Chevre'), (SELECT id FROM ingredient WHERE name='Sauce ranch'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Ptit Wrap Ranch'), (SELECT id FROM ingredient WHERE name='Tortilla'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Ptit Wrap Ranch'), (SELECT id FROM ingredient WHERE name='Filet de poulet pane'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Ptit Wrap Ranch'), (SELECT id FROM ingredient WHERE name='Cheddar'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Ptit Wrap Ranch'), (SELECT id FROM ingredient WHERE name='Salade'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Ptit Wrap Ranch'), (SELECT id FROM ingredient WHERE name='Oignon'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Ptit Wrap Ranch'), (SELECT id FROM ingredient WHERE name='Sauce ranch'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Petite Salade'), (SELECT id FROM ingredient WHERE name='Salade'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Petite Salade'), (SELECT id FROM ingredient WHERE name='Tomate'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Petite Salade'), (SELECT id FROM ingredient WHERE name='Roquette'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Cesar Classic'), (SELECT id FROM ingredient WHERE name='Salade'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Cesar Classic'), (SELECT id FROM ingredient WHERE name='Filet de poulet pane'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Cesar Classic'), (SELECT id FROM ingredient WHERE name='Emmental'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Cesar Classic'), (SELECT id FROM ingredient WHERE name='Tomate'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Cesar Classic'), (SELECT id FROM ingredient WHERE name='Sauce ranch'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Cesar Classic'), (SELECT id FROM ingredient WHERE name='Tranche de bacon'), 1, 1, 1, 1, 80),
  ((SELECT id FROM product WHERE name='Italienne Mozza'), (SELECT id FROM ingredient WHERE name='Salade'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Italienne Mozza'), (SELECT id FROM ingredient WHERE name='Mozzarella'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Italienne Mozza'), (SELECT id FROM ingredient WHERE name='Tomate'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Italienne Mozza'), (SELECT id FROM ingredient WHERE name='Roquette'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Italienne Mozza'), (SELECT id FROM ingredient WHERE name='Sauce deluxe'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Brownie'), (SELECT id FROM ingredient WHERE name='Brownie'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Cheesecake chocolat M&M''S'), (SELECT id FROM ingredient WHERE name='Cheesecake'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Cheesecake chocolat M&M''S'), (SELECT id FROM ingredient WHERE name='Topping chocolat'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Cheesecake Fraise'), (SELECT id FROM ingredient WHERE name='Cheesecake'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Cookie'), (SELECT id FROM ingredient WHERE name='Cookie'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Donut'), (SELECT id FROM ingredient WHERE name='Donut'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Macarons'), (SELECT id FROM ingredient WHERE name='Macaron'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='MC Fleury'), (SELECT id FROM ingredient WHERE name='Glace McFleury'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='MC Fleury'), (SELECT id FROM ingredient WHERE name='Topping chocolat'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Muffin'), (SELECT id FROM ingredient WHERE name='Muffin'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Sunday'), (SELECT id FROM ingredient WHERE name='Glace sundae'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Sunday'), (SELECT id FROM ingredient WHERE name='Topping chocolat'), 1, 1, 1, 0, 0),
  ((SELECT id FROM product WHERE name='Classic Barbecue'), (SELECT id FROM ingredient WHERE name='Dosette Barbecue'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Classic Moutarde'), (SELECT id FROM ingredient WHERE name='Dosette Moutarde'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Creamy Deluxe'), (SELECT id FROM ingredient WHERE name='Dosette Deluxe'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Ketchup'), (SELECT id FROM ingredient WHERE name='Dosette Ketchup'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Chinoise'), (SELECT id FROM ingredient WHERE name='Dosette Chinoise'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Curry'), (SELECT id FROM ingredient WHERE name='Dosette Curry'), 1, 1, 0, 0, 0),
  ((SELECT id FROM product WHERE name='Pommes Frites'), (SELECT id FROM ingredient WHERE name='Dosette Pommes Frites'), 1, 1, 0, 0, 0);

