<?php

declare(strict_types=1);

namespace App\Health;

/**
 * Source unique des exigences de securite par route (page "Sante de l'API").
 * Une ligne par route enregistree dans le routeur (src/app/Core/routes.php),
 * 157 au total. App\Health\RouteMap la fusionne avec App\Core\Router::routes()
 * pour construire la carte affichee ; les tests de securite (RouteMatrixTest,
 * les nouveaux tests sous tests/Unit/Health/Route*) la lisent comme reference,
 * au lieu de tabuler ces valeurs une seconde fois.
 *
 * Chaque valeur reprend EXACTEMENT ce que verifie le controleur reel de la
 * route : `guard('...')`/`guardApi('...')` (ou sa constante PERMISSION) pour la
 * permission, `Csrf::validate()` ou son equivalent JSON pour csrf, `PinGate`
 * pour pin/reauth. Un ecart entre cette table et le controleur est un bug de
 * cette table (le controleur fait foi), jamais l'inverse.
 */
final class RouteSecurity
{
    /**
     * [methode, chemin brut, sans_compte, permission, csrf ('header'|'form'|null),
     * pin ('always'|'price'|null), reauth ('password'|null)].
     *
     * @var list<array{0: string, 1: string, 2: bool, 3: ?string, 4: ?string, 5: ?string, 6: ?string}>
     */
    public const ENTRIES = [
    ['GET', '/', true, null, null, null, null],
    ['GET', '/api/health', true, null, null, null, null],
    ['GET', '/admin/health', false, 'role.manage', null, null, null],
    ['GET', '/admin/api/health', false, 'role.manage', null, null, null],
    ['GET', '/login', true, null, null, null, null],
    ['POST', '/login', true, null, 'form', null, null],
    // sans_compte = true : AuthController::logout() ne verifie QUE le jeton CSRF
    // (Csrf::validate), jamais la session (pas de guard()/sessionGuard()->check()) --
    // ecart releve par le chantier D (tests HTML), verifie ici dans le controleur,
    // corrige contre scratchpad/routes-final.json qui le donnait a tort a false.
    ['POST', '/logout', true, null, 'form', null, null],
    ['GET', '/forgot_password', true, null, null, null, null],
    ['POST', '/forgot_password', true, null, 'form', null, null],
    ['GET', '/reset_password', true, null, null, null, null],
    ['POST', '/reset_password', true, null, 'form', null, null],
    ['POST', '/api/orders', true, null, null, null, null],
    ['POST', '/api/orders/{number}/pay', true, null, null, null, null],
    ['GET', '/api/orders/{number}', true, null, null, null, null],
    ['GET', '/api/categories', true, null, null, null, null],
    ['GET', '/api/products', true, null, null, null, null],
    ['GET', '/api/products/{id}', true, null, null, null, null],
    ['GET', '/api/menus', true, null, null, null, null],
    ['GET', '/api/menus/{id}', true, null, null, null, null],
    ['GET', '/api/allergens', true, null, null, null, null],
    ['GET', '/admin/me', false, null, null, null, null],
    ['GET', '/admin/dashboard', false, null, null, null, null],
    ['GET', '/admin/stats', false, 'stats.read', null, null, null],
    ['GET', '/admin/orders', false, 'order.read', null, null, null],
    ['POST', '/admin/orders/{number}/deliver', false, 'order.deliver', 'form', null, null],
    ['POST', '/admin/orders/{number}/ready', false, 'order.read', 'form', null, null],
    ['GET', '/admin/orders/{number}/cancel', false, 'order.cancel', null, null, null],
    ['POST', '/admin/orders/{number}/cancel', false, 'order.cancel', 'form', 'always', null],
    ['GET', '/kitchen/display', false, 'order.read', null, null, null],
    ['GET', '/counter/orders', false, 'order.create', null, null, null],
    ['GET', '/counter/orders/new', false, 'order.create', null, null, null],
    ['POST', '/counter/orders', false, 'order.create', 'form', null, null],
    ['GET', '/drive/orders', false, 'order.create', null, null, null],
    ['GET', '/drive/orders/new', false, 'order.create', null, null, null],
    ['POST', '/drive/orders', false, 'order.create', 'form', null, null],
    ['GET', '/admin/users', false, 'user.read', null, null, null],
    ['GET', '/admin/users/new', false, 'user.create', null, null, null],
    ['POST', '/admin/users', false, 'user.create', 'form', 'always', null],
    ['GET', '/admin/users/{id}/edit', false, 'user.update', null, null, null],
    ['POST', '/admin/users/{id}', false, 'user.update', 'form', 'always', null],
    ['GET', '/admin/users/{id}/deactivate', false, 'user.deactivate', null, null, null],
    ['POST', '/admin/users/{id}/deactivate', false, 'user.deactivate', 'form', 'always', null],
    ['GET', '/admin/users/{id}/reset-pin', false, 'user.update', null, null, null],
    ['POST', '/admin/users/{id}/reset-pin', false, 'user.update', 'form', 'always', null],
    ['GET', '/admin/users/{id}/erase', false, 'user.update', null, null, null],
    ['POST', '/admin/users/{id}/erase', false, 'user.update', 'form', 'always', null],
    ['GET', '/admin/roles', false, 'role.manage', null, null, null],
    ['GET', '/admin/roles/new', false, 'role.manage', null, null, null],
    ['POST', '/admin/roles', false, 'role.manage', 'form', 'always', null],
    ['GET', '/admin/roles/{id}/edit', false, 'role.manage', null, null, null],
    ['POST', '/admin/roles/{id}', false, 'role.manage', 'form', 'always', null],
    ['GET', '/admin/categories', false, 'category.manage', null, null, null],
    ['GET', '/admin/categories/new', false, 'category.manage', null, null, null],
    ['POST', '/admin/categories', false, 'category.manage', 'form', null, null],
    ['GET', '/admin/categories/{id}/edit', false, 'category.manage', null, null, null],
    ['POST', '/admin/categories/{id}', false, 'category.manage', 'form', null, null],
    ['POST', '/admin/categories/{id}/toggle', false, 'category.manage', 'form', null, null],
    ['POST', '/admin/categories/{id}/move', false, 'category.manage', 'form', null, null],
    ['GET', '/admin/profile/pin', false, null, null, null, null],
    ['POST', '/admin/profile/pin', false, null, 'form', null, 'password'],
    ['GET', '/admin/privacy', false, null, null, null, null],
    ['GET', '/admin/products', false, 'product.read', null, null, null],
    ['GET', '/admin/products/by-category', false, 'product.read', null, null, null],
    ['GET', '/admin/products/new', false, 'product.create', null, null, null],
    ['POST', '/admin/products', false, 'product.create', 'form', null, null],
    ['GET', '/admin/products/{id}/edit', false, 'product.update', null, null, null],
    ['POST', '/admin/products/{id}', false, 'product.update', 'form', 'price', null],
    ['GET', '/admin/products/{id}/delete', false, 'product.delete', null, null, null],
    ['POST', '/admin/products/{id}/delete', false, 'product.delete', 'form', 'always', null],
    ['POST', '/admin/products/{id}/move', false, 'product.update', 'form', null, null],
    ['GET', '/admin/products/{id}/recipe', false, 'ingredient.manage', null, null, null],
    ['POST', '/admin/products/{id}/recipe', false, 'ingredient.manage', 'form', null, null],
    ['GET', '/admin/products/import', false, 'product.create', null, null, null],
    ['GET', '/admin/products/import/template', false, 'product.create', null, null, null],
    ['POST', '/admin/products/import/preview', false, 'product.create', 'form', null, null],
    ['POST', '/admin/products/import/confirm', false, 'product.create', 'form', 'price', null],
    ['GET', '/admin/menus', false, 'menu.read', null, null, null],
    ['GET', '/admin/menus/new', false, 'menu.create', null, null, null],
    ['POST', '/admin/menus', false, 'menu.create', 'form', null, null],
    ['GET', '/admin/menus/{id}/edit', false, 'menu.update', null, null, null],
    ['POST', '/admin/menus/{id}', false, 'menu.update', 'form', null, null],
    ['POST', '/admin/menus/{id}/toggle', false, 'menu.update', 'form', null, null],
    ['GET', '/admin/menus/{id}/delete', false, 'menu.delete', null, null, null],
    ['POST', '/admin/menus/{id}/delete', false, 'menu.delete', 'form', 'always', null],
    ['GET', '/admin/ingredients', false, 'stock.read', null, null, null],
    ['GET', '/admin/ingredients/new', false, 'ingredient.manage', null, null, null],
    ['POST', '/admin/ingredients', false, 'ingredient.manage', 'form', null, null],
    ['GET', '/admin/ingredients/{id}/edit', false, 'ingredient.manage', null, null, null],
    ['POST', '/admin/ingredients/{id}', false, 'ingredient.manage', 'form', null, null],
    ['POST', '/admin/ingredients/{id}/toggle', false, 'ingredient.manage', 'form', null, null],
    ['GET', '/admin/ingredients/{id}/delete', false, 'ingredient.manage', null, null, null],
    ['POST', '/admin/ingredients/{id}/delete', false, 'ingredient.manage', 'form', null, null],
    ['GET', '/admin/ingredients/{id}/restock', false, 'stock.manage', null, null, null],
    ['POST', '/admin/ingredients/{id}/restock', false, 'stock.manage', 'form', null, null],
    ['POST', '/admin/ingredients/{id}/thresholds', false, 'stock.manage', 'form', null, null],
    ['GET', '/admin/ingredients/{id}/inventory', false, 'stock.count', null, null, null],
    ['POST', '/admin/ingredients/{id}/inventory', false, 'stock.count', 'form', 'always', null],
    ['GET', '/admin/ingredients/{id}/adjust', false, 'stock.count', null, null, null],
    ['POST', '/admin/ingredients/{id}/adjust', false, 'stock.count', 'form', 'always', null],
    ['GET', '/admin/ingredients/{id}/movements', false, 'stock.read', null, null, null],
    ['POST', '/admin/ingredients/{id}/enrich', false, 'ingredient.manage', 'form', null, null],
    ['POST', '/admin/ingredients/{id}/allergens', false, 'ingredient.manage', 'form', null, null],
    ['POST', '/admin/api/auth/login', true, null, null, null, null],
    ['POST', '/admin/api/auth/logout', false, null, 'header', null, null],
    ['GET', '/admin/api/auth/me', false, null, null, null, null],
    ['GET', '/admin/api/categories', false, 'category.manage', null, null, null],
    ['GET', '/admin/api/categories/{id}', false, 'category.manage', null, null, null],
    ['POST', '/admin/api/categories', false, 'category.manage', 'header', null, null],
    ['PUT', '/admin/api/categories/{id}', false, 'category.manage', 'header', null, null],
    ['DELETE', '/admin/api/categories/{id}', false, 'category.manage', 'header', null, null],
    ['POST', '/admin/api/categories/{id}/toggle', false, 'category.manage', 'header', null, null],
    ['POST', '/admin/api/categories/{id}/move', false, 'category.manage', 'header', null, null],
    ['GET', '/admin/api/products', false, 'product.read', null, null, null],
    ['GET', '/admin/api/products/{id}', false, 'product.read', null, null, null],
    ['POST', '/admin/api/products', false, 'product.create', 'header', null, null],
    ['PUT', '/admin/api/products/{id}', false, 'product.update', 'header', 'price', null],
    ['DELETE', '/admin/api/products/{id}', false, 'product.delete', 'header', 'always', null],
    ['POST', '/admin/api/products/{id}/move', false, 'product.update', 'header', null, null],
    ['GET', '/admin/api/products/{id}/recipe', false, 'ingredient.manage', null, null, null],
    ['PUT', '/admin/api/products/{id}/recipe', false, 'ingredient.manage', 'header', null, null],
    ['GET', '/admin/api/products/import/template', false, 'product.create', null, null, null],
    ['POST', '/admin/api/products/import', false, 'product.create', 'header', 'price', null],
    ['GET', '/admin/api/menus', false, 'menu.read', null, null, null],
    ['GET', '/admin/api/menus/{id}', false, 'menu.read', null, null, null],
    ['POST', '/admin/api/menus', false, 'menu.create', 'header', null, null],
    ['PUT', '/admin/api/menus/{id}', false, 'menu.update', 'header', null, null],
    ['DELETE', '/admin/api/menus/{id}', false, 'menu.delete', 'header', 'always', null],
    ['POST', '/admin/api/menus/{id}/toggle', false, 'menu.update', 'header', null, null],
    ['GET', '/admin/api/ingredients', false, 'stock.read', null, null, null],
    ['GET', '/admin/api/ingredients/{id}', false, 'stock.read', null, null, null],
    ['POST', '/admin/api/ingredients', false, 'ingredient.manage', 'header', null, null],
    ['PUT', '/admin/api/ingredients/{id}', false, 'ingredient.manage', 'header', null, null],
    ['DELETE', '/admin/api/ingredients/{id}', false, 'ingredient.manage', 'header', null, null],
    ['POST', '/admin/api/ingredients/{id}/restock', false, 'stock.manage', 'header', null, null],
    ['POST', '/admin/api/ingredients/{id}/toggle', false, 'ingredient.manage', 'header', null, null],
    ['PUT', '/admin/api/ingredients/{id}/thresholds', false, 'stock.manage', 'header', null, null],
    ['POST', '/admin/api/ingredients/{id}/inventory', false, 'stock.count', 'header', 'always', null],
    ['POST', '/admin/api/ingredients/{id}/adjust', false, 'stock.count', 'header', 'always', null],
    ['PUT', '/admin/api/ingredients/{id}/allergens', false, 'ingredient.manage', 'header', null, null],
    ['GET', '/admin/api/users', false, 'user.read', null, null, null],
    ['GET', '/admin/api/users/{id}', false, 'user.read', null, null, null],
    ['POST', '/admin/api/users', false, 'user.create', 'header', 'always', null],
    ['PUT', '/admin/api/users/{id}', false, 'user.update', 'header', 'always', null],
    ['DELETE', '/admin/api/users/{id}', false, 'user.deactivate', 'header', 'always', null],
    ['POST', '/admin/api/users/{id}/reset-pin', false, 'user.update', 'header', 'always', null],
    ['POST', '/admin/api/users/{id}/erase', false, 'user.update', 'header', 'always', null],
    ['GET', '/admin/api/roles', false, 'role.manage', null, null, null],
    ['GET', '/admin/api/roles/{id}', false, 'role.manage', null, null, null],
    ['POST', '/admin/api/roles', false, 'role.manage', 'header', 'always', null],
    ['PUT', '/admin/api/roles/{id}', false, 'role.manage', 'header', 'always', null],
    ['GET', '/admin/api/orders', false, 'order.read', null, null, null],
    ['GET', '/admin/api/orders/{number}', false, 'order.read', null, null, null],
    ['POST', '/admin/api/orders', false, 'order.create', 'header', null, null],
    ['POST', '/admin/api/orders/{number}/ready', false, 'order.read', 'header', null, null],
    ['POST', '/admin/api/orders/{number}/deliver', false, 'order.deliver', 'header', null, null],
    ['POST', '/admin/api/orders/{number}/cancel', false, 'order.cancel', 'header', 'always', null],
    ['GET', '/admin/api/stats', false, 'stats.read', null, null, null],
    ];
}
